"""S09+S10: utterances segments notes provenance assets

Revision ID: c58ea6212bc5
Revises: a6f03a872c52
Create Date: 2026-09-12 02:34:54.106696

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c58ea6212bc5"
down_revision: str | Sequence[str] | None = "a6f03a872c52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "note_assets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("note_section_id", sa.UUID(), nullable=False),
        sa.Column("asset_type", sa.String(length=50), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=True),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("licence", sa.String(length=100), nullable=True),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("is_ai_generated", sa.Boolean(), nullable=False),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("ocr_confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(asset_type != 'web_image') OR (source_url IS NOT NULL AND licence IS NOT NULL)",
            name=op.f("ck_note_assets_ck_web_image_licence"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_note_assets")),
    )
    op.create_table(
        "note_provenance",
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("note_section_id", sa.UUID(), nullable=False),
        sa.Column("utterance_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("subject_id", "id", name=op.f("pk_note_provenance")),
    )
    op.create_table(
        "note_sections",
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("heading", sa.Text(), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("subject_id", "id", name=op.f("pk_note_sections")),
    )
    op.create_table(
        "segments",
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("start_utt", sa.UUID(), nullable=False),
        sa.Column("end_utt", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=True),
        sa.Column("boundary_score", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_segments_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("subject_id", "id", name=op.f("pk_segments")),
    )
    op.create_table(
        "utterances",
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("asr_confidence", sa.Float(), nullable=True),
        sa.Column("speaker_tag", sa.String(length=10), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("embed_model_ver", sa.String(length=50), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=True),
        sa.Column("is_relevant", sa.Boolean(), nullable=True),
        sa.Column("filter_reason", sa.String(length=100), nullable=True),
        sa.Column("outlier_score", sa.Float(), nullable=True),
        sa.Column("asr_agreement", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_utterances_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("subject_id", "id", name=op.f("pk_utterances")),
        sa.UniqueConstraint("subject_id", "session_id", "seq", name="uq_utterance_session_seq"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("utterances")
    op.drop_table("segments")
    op.drop_table("note_sections")
    op.drop_table("note_provenance")
    op.drop_table("note_assets")
    # ### end Alembic commands ###
