"""Note-quality reward R(notes, flashcards, transcript) -> [0, 1].

Flashcards are generated by the same local model from the notes it wrote, so
scoring notes->cards alone only measures self-consistency (vague notes yield
vague cards that "cover" them perfectly). Every term here is therefore scored
against the SOURCE TRANSCRIPT (the utterances T5 kept), and the LLM-judged terms
are meant to run on a different model family (see judge.py).

All weights/thresholds are unvalidated priors (docs/audit/self-improving-loop.md):
R must be shown to correlate with human ratings before anything optimizes it.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

# ASSUMED priors -- not tuned.
COVERAGE_TAU = 0.5
WEIGHTS: dict[str, float] = {
    "coverage": 0.30,  # cards cover the transcript's semantic space
    "note_coverage": 0.20,  # notes cover it too (catches vague/short notes)
    "diversity": 0.15,  # cards are not near-duplicates
    "validity": 0.20,  # judge: card answer supported by its cited source
    "provenance": 0.15,  # judge: note section supported by cited utterances
}


def _unit(m: np.ndarray) -> np.ndarray:
    norms = np.linalg.norm(m, axis=1, keepdims=True)
    return m / np.where(norms == 0, 1.0, norms)


def coverage(utterance_emb: np.ndarray, item_emb: np.ndarray, tau: float = COVERAGE_TAU) -> float:
    """Fraction of transcript utterances whose best-matching item has cosine >= tau.

    Range [0, 1]. Failure mode: items that quote the transcript verbatim maximize it.
    """
    if len(utterance_emb) == 0 or len(item_emb) == 0:
        return 0.0
    sims = _unit(utterance_emb) @ _unit(item_emb).T
    return float(np.mean(sims.max(axis=1) >= tau))


def diversity(item_emb: np.ndarray) -> float:
    """1 - mean pairwise cosine among cards, clipped to [0, 1].

    Failure mode: unrelated random cards maximize it -- hence it is only ever
    combined with coverage (geometric mean), never used alone.
    """
    n = len(item_emb)
    if n < 2:
        return 0.0
    u = _unit(item_emb)
    sims = u @ u.T
    mean_pair = (sims.sum() - n) / (n * (n - 1))
    return float(np.clip(1.0 - mean_pair, 0.0, 1.0))


@dataclass(frozen=True)
class RewardResult:
    reward: float
    terms: dict[str, float | None]
    judged: bool


def aggregate(terms: dict[str, float | None]) -> RewardResult:
    """Weighted geometric mean over the terms that are present.

    Geometric so any collapsed term (0) collapses R -- a deck can't buy back
    zero coverage with high diversity. Missing (unjudged) terms are dropped and
    the remaining weights renormalized; `judged` records whether the judge terms
    were included so unjudged and judged scores are never silently mixed.
    """
    present = {k: v for k, v in terms.items() if v is not None and k in WEIGHTS}
    if not present:
        return RewardResult(0.0, terms, False)
    total_w = sum(WEIGHTS[k] for k in present)
    if any(v <= 0 for v in present.values()):
        reward = 0.0
    else:
        reward = float(np.exp(sum(WEIGHTS[k] * np.log(v) for k, v in present.items()) / total_w))
    return RewardResult(reward, terms, "validity" in present and "provenance" in present)
